# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170106_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location default', max_length=128),
        ),
    ]
